### ISSUE TITLE
エディターから地図画像のアップロードができない

### ISSUE THREAD

**Issue by NbtKmy** [code4history/MaplatEditor#20]
Windows10にMaplatEditorをインストールしました。地図のメタデータの記入・保存は問題なくできましたが、画像データ（jpgで50MBくらいのおおきさ）がアップロードできず、PCがクラッシュしてしまいます。

**Comment by kochizufan** [comment]
申し訳ありません、どのくらいのサイズの画像まで対応できるかはPCの性能に左右されるようで、解決するのは少々難しいようです。
当方の環境でデータ化できるかもしれませんので、以下のように対応いただけないでしょうか。

1. Maplatエディタでメタデータなどだけ設定してセーブする
2. 地図データ保存先のmapsフォルダの中にある、「地図ID.json」ファイルを回収
3. 地図画像と地図ID.jsonを一緒にzip等で圧縮
4. 大容量ファイルを送れる宅ファイル便などのサービスを使って、rekishikokudo@tilemap.jpのアドレスまでzipファイルを送信

これで画像をいただければ、こちらでデータ化を試してみます。

将来的には、手元でデータ化できない場合にサーバに転送してデータ化できるようなサービスも検討してみます。

**Comment by kochizufan** [comment]
0.2.2でタイル化処理軽量化対応
