### ISSUE TITLE
ボタン名称の変更提案

### ISSUE THREAD

**Issue by tankaru** [code4history/MaplatEditor#23]
Windowsパッケージ版を使用させていただきました。
使用する際にボタン名で少し戸惑ったので、変更を提案いたします。

・地図アップロード
この操作で指定した画像が、どこかのサーバにアップロードされてしまのではないかと感じました。
「地図画像を開く」「地図画像を読み込む」などに変更するのはいかがでしょうか。

・地図データダウンロード
OSMや地理院地図などの地図タイルをダウンロードするのではないかと思いました。
「エクスポート」などに変更するのはいかがでしょうか。

ご検討ください。

**Comment by kochizufan** [comment]
ありがとうございます。
次版で採用させていただきます。
いくつかバグを見つけているので、おそらく数週間以内に反映すると思います。

**Comment by kochizufan** [comment]
既に内部の開発では取り込んでおり、それぞれ「地図画像追加」「地図データエクスポート」と変更しました。
次のバージョンの作成ですが、Windows向けに怪しいインストーラ扱いされないように、インストーラに署名をしようと考えているのですが、証明書の購入に公的機関の証明の取得など時間がかかるので、実際の適用には少し時間がかかりそうです。

**Comment by tankaru** [comment]
ご対応いただきましてありがとうございました。
インストーラに署名を付けるのは結構大変なのですね。知りませんでした。

**Comment by kochizufan** [comment]
Release 0.4.2で対応しました。
（Windowsインストーラ署名は証明書の取得がかなり大変なようで見送りました）
