### ISSUE TITLE
緯度経度の入力で、正確な地図側の該当箇所へ移動したい

### ISSUE THREAD

**Issue by snowdrops89** [code4history/MaplatEditor#31]
大概の地図アプリで出来るような、緯度経度の検索で場所移動できて、GSMのように、そのポイントに＋マークなど出ると良い感じ。
　川や道路などに沿ってマッピングしている場合はそうでもないですが、史跡の跡地など、古地図にはあって現在の地図上からは失われているが、どこにあったか明確に緯度経度の情報が分かってる、データとして持ってる、みたいなポイントって結構あると思います。
　地図上をウロウロ探すより、数値を入力して、びゅっとその場所へ移動して、点を打ちたい感じです。
　現状ですと、別の地図アプリで場所を検索し、エディタに戻ってその同じ場所を探して点を打つ、みたいな感じで二度手間なのです。

**Comment by kochizufan** [comment]
#32 と同じ対応なのですが、
![image](https://user-images.githubusercontent.com/2221431/116915983-b01a2d00-ac87-11eb-87b9-8cd3fe227e57.png)

ピンをクリックするとそのIDのマーカーの座標が地図の下に表示されて、かつ表示の値を直接編集すればピンの位置を動かせるようにしました。

ご意見あればいただけると嬉しいです。

**Comment by kochizufan** [comment]
https://github.com/code4history/MaplatEditor/releases/tag/v0.5.1
で対応しました
