### ISSUE TITLE
対応点マーカーの位置情報を見たい

### ISSUE THREAD

**Issue by snowdrops89** [code4history/MaplatEditor#32]
クリックするとどこかに表示されるとか、GoogleMapの地図上のように、右クリックメニューに入るとか、どんな形でも良いのですが、その点の正確な地図上での緯度経度が、後からも別の地図アプリと見比べたりしなくても、エディタ上で確認出来るようになると嬉しいです。

**Comment by kochizufan** [comment]
![image](https://user-images.githubusercontent.com/2221431/116915358-e1462d80-ac86-11eb-9962-8c7db3e71e35.png)

こちらの実装ですが、どういうUIにするか悩んだ挙句、キャプチャ画像のような感じにしました。
経緯度の場所を表示する機能というよりも、ピンの場所そのものを確認して編集できるようにしたいという意味と理解しましたので、ピンをクリックするとそのIDのマーカーの座標が地図の下に表示されて、かつ表示の値を直接編集すればピンの位置を動かせるようにしました。

ご意見あればいただけると嬉しいです。

**Comment by kochizufan** [comment]
https://github.com/code4history/MaplatEditor/releases/tag/v0.5.1
で対応しました
