### ISSUE TITLE
対応点編集画面の地図を回転したい

### ISSUE THREAD

**Issue by snowdrops89** [code4history/MaplatEditor#33]
古地図って大概北が上にはなってないので、古地図側とベース地図側と、向きが違ってしまうので、わたしのような基本地図の読めない人間は始終、アレ？　どっち？　こっち？　と混乱してしまうのでした（汗）
　古地図を何度回転させて表示するとか、こちら側を北として表示するとか、そういった設定で、現代の地図と方向を合わせることができると助かります。

**Comment by kochizufan** [comment]
返答が遅くなりました。
この機能は実はもうついています。

古地図側でもベース地図側でもいいですが、MacだとCommand、WindowsだとAltキーを押しながら、マウスで地図をドラッグすると、地図をくるくる回転させられます。
ただ、機能の存在をどうやって周知するかは妙案がなく、ちょっと放置しています。
