### ISSUE TITLE
対応点の一括登録

### ISSUE THREAD

**Issue by nakamura196** [code4history/MaplatEditor#43]
大変有益なアプリケーションの開発、ありがとうございます。

MaplatEditorの初心者で、基本的な質問で恐縮ですが、対応点をCSVファイルなどから一括登録する方法はございますか？

どうぞよろしくお願いいたします。

**Comment by kochizufan** [comment]
お世話になります。

現状はございませんが、対応させることはできると思います。

半月位程度でお時間いただけないでしょうか。

よろしくお願いいたします。

**Comment by nakamura196** [comment]
早速お返事くださりありがとうございます。また、ご対応いただけるとのこと、大変嬉しく思います。

お手数をおかけしますが、何卒よろしくお願いいたします。

**Comment by kochizufan** [comment]
とりあえず動作するものができたはずなのですが、正式リリース前にこんな感じでよいか先に使っていただこうかと思いました。
仮リリース版を提供したいのですが、Windows/Mac Intel/Mac M1のいずれがよいでしょうか？

**Comment by nakamura196** [comment]
早速ありがとうございます！
普段はMac M１を使用しています。
楽しみにしております。

**Comment by kochizufan** [comment]
https://t.tilemap.jp/maplat/dist/RC/MaplatEditor-0.6.1-arm64.dmg

にインストーラを用意いたしました。

すみません、手っ取り早く仕上げたので以下の状況です
＊QGISのジオリファレンサで作ったファイルも読み込めるよう書かれているようなUIですが、実際のテストはまだ、単に4列座標情報がヘッダなしで並んでるような普通のCSVでしか行っていません
＊開発に使ったWindowsでは上記が動作することを確認しましたが、M1 Macではコンパイル＆インストールが完了するところまでテストしただけで、新規機能のテストはやっていません

動作ですが、対応点編集タブの隣にデータ入出力タブを設けたので、そこにCSV対応UIができています
CSVのどのカラムが座標情報か（非技術者が使うことも想定して先頭は0ではなく1にしました）指定するなど必要情報を設定の上、CSVを指定すると読み込むようになっています
ご確認ください

**Comment by nakamura196** [comment]
ありがとうございます！早速試させていただきます。

**Comment by nakamura196** [comment]
本件試させていただきましたが、無事対応点を一括登録できました。
この度は急なお願いにも関わらず、ご対応くださり本当にありがとうございました！

**Comment by kochizufan** [comment]
0.6.2で正式公開しました
